language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-testing.txt"
  - "pip install coveralls"
  - "pip install codacy-coverage"
  - "python setup.py develop --no-deps"
script:
  - nosetests --with-coverage --cover-package=threatingestor --cover-xml
  - python setup.py checkdocs
  - cd docs/; make SPHINXOPTS=-W html
  - cd ..
after_success:
  - python-codacy-coverage
